project 'YBROptionViewDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
target 'YBROptionViewDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YBROptionViewDemo
  pod 'YBRConfigurationModule', :path =>'../../../YBRConfigurationModule'
  pod 'YBROptionView', :path =>'../../../YBROptionView'
  
  pod 'Masonry'

end
